project:
  render:
    - index.qmd
    - current/tej.qmd
    - current/tts.qmd
    - current/tas.qmd
    - 2026-27/semester-1/period-1/tej/full.qmd
    - 2026-27/semester-1/period-1/tts/full.qmd
    - 2026-27/semester-1/period-1/tas/full.qmd
    - handouts/about-me-active-listening.qmd
